drop table if exists hits;
drop table if exists apps;

create table apps
(
    app_id bigint not null generated by default as identity,
    app_name varchar(24) not null,
    constraint apps_pk primary key (app_id)
);

create table hits
(
    hit_id bigint not null generated by default as identity,
    hit_app_id bigint not null,
    hit_uri varchar(255) not null,
    hit_ip varchar(16) not null,
    hit_timestamp timestamp(0) without time zone not null,
    constraint hits_pk primary key (hit_id),
    constraint hits_fk_app_id foreign key (hit_app_id) references apps(app_id) on delete cascade
);