drop table if exists compilations_events;
drop table if exists compilations;
drop table if exists requests;
drop table if exists events;
drop table if exists locations;
drop table if exists categories;
drop table if exists users;

create table users
(
    user_id bigint not null generated by default as identity,
    user_name varchar(255) not null,
    user_email varchar(255) not null unique,
    constraint users_pk primary key (user_id)
);

create table categories
(
    category_id bigint not null generated by default as identity,
    category_name varchar(50) not null unique,
    constraint categories_pk primary key (category_id)
);

create table locations
(
    location_id bigint not null generated by default as identity,
    location_lat float4 not null,
    location_lon float4 not null,
    constraint locations_pk primary key (location_id)
);

create table events
(
    event_id bigint not null generated by default as identity,
    event_title varchar(120) not null,
    event_annotation varchar(2000) not null,
    event_description varchar(7000) not null,
    event_initiator_id bigint not null,
    event_category_id bigint not null,
    event_location_id bigint not null,
    event_event_date timestamp(0) without time zone not null,
    event_created_on timestamp(0) without time zone,
    event_published_on timestamp(0) without time zone,
    event_participant_limit integer not null default 0,
    event_paid bool not null default false,
    event_request_moderation bool not null default true,
    event_state varchar(50) not null,
    constraint events_pk primary key (event_id),
    constraint events_fk_initiator_id foreign key (event_initiator_id) references users(user_id) on delete cascade,
    constraint events_fk_category_id foreign key (event_category_id) references categories(category_id),
    constraint events_fk_location_id foreign key (event_location_id) references locations(location_id)
);

create table requests
(
    request_id bigint not null generated by default as identity,
    request_created timestamp without time zone not null,
    request_event_id bigint not null,
    request_requester_id bigint not null,
    request_status varchar(50) not null,
    constraint requests_pk primary key (request_id),
    constraint requests_fk_event_id foreign key (request_event_id) references events(event_id) on delete cascade,
    constraint requests_fk_requester_id foreign key (request_requester_id) references users(user_id) on delete cascade
);

create table compilations
(
    compilation_id bigint not null generated by default as identity,
    compilation_pinned bool not null default false,
    compilation_title varchar(50) not null unique,
    constraint compilations_pk primary key (compilation_id)
);

create table compilations_events
(
    compilation_id bigint not null,
    event_id bigint not null,
    constraint compilations_events_pk primary key (compilation_id, event_id),
    constraint compilations_events_compilation_id_fk foreign key (compilation_id) references compilations(compilation_id),
    constraint compilations_events_event_id_fk foreign key (event_id) references events(event_id)
);