version: '3.1'
services:
  stats-server:
    build: stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-server-db
      - POSTGRES_USER=pg-user
      - POSTGRES_PASSWORD=pg-password

  stats-db:
    image: postgres:14-alpine
    container_name: stats-server-db
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: "stats-server-db"
      POSTGRES_USER: "pg-user"
      POSTGRES_PASSWORD: "pg-password"

  ewm-service:
    build: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main-service-db
      - POSTGRES_USER=pg-user
      - POSTGRES_PASSWORD=pg-password

  ewm-db:
    image: postgres:14-alpine
    container_name: main-service-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: "main-service-db"
      POSTGRES_USER: "pg-user"
      POSTGRES_PASSWORD: "pg-password"